apiVersion: v1
kind: ConfigMap
metadata:
  name: "cart"
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"


apiVersion: apps/v1
kind : Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "cart"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "cart"
    template:
      metadata:
        labels:
          project: "roboshop"
          tier: "data"
          app: "cart"     
      spec:
        containers:
        - name: cart
          image: jagadevops321/cart:v1
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: "cart"

apiVersion: v1
kind: Service
metadata:
  name: "cart"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "cart" 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 

