apiVersion: v1
kind: ConfigMap
metadata:
  name: "shipping"
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
---

apiVersion: apps/v1
kind : Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "shipping"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "shipping"
  template:
    metadata:
      labels:
        project: "roboshop"
        tier: "data"
        app: "shipping"     
    spec:
      containers:
      - name: shipping
        image: jagadevops321/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: "shipping"
---
apiVersion: v1
kind: Service
metadata:
  name: "shipping"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "shipping" 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 

