apiVersion: v1
kind: ConfigMap
metadata:
  name: "mysql"
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"

------------------

apiVersion: v1
kind: Secret
metadata:
  name: "mysql"
  namespace: roboshop
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==


-------------------

apiVersion: apps/v1
kind : Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "mysql"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "mysql"
    template:
      metadata:
        labels:
          project: "roboshop"
          tier: "data"
          app: "mysql"     
      spec:
        containers:
        - name: mysql
          image: jagadevops321/mysql:v1
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: "mysql"
          - secretRef:
              name: "mysql"

------
apiVersion: v1
kind: Service
metadata:
  name: "mysql"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "mysql" 
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
 

