apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
----------------------------------------------------------
apiVersion: apps/v1
kind : Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "rabbitmq"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "rabbitmq"
    template:
      metadata:
        labels:
          project: "roboshop"
          tier: "data"
          app: "rabbitmq"     
      spec:
        containers:
        - name: rabbitmq
          image: rabbitmq
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: rabbitmq
------

apiVersion: v1
kind: Service
metadata:
  name: "rabbitmq"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "rabbitmq" 
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
 

