apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: roboshop
labels:
  course: "devops"
  trainer: "siva"
spec:
  containers:
  - name: demo-con
    image: nginx
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    env:
    - name: "course"
      value: "devops"
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: demo-config
    envFrom:
    - secretRef:
        name: demo-secret


    