apiVersion: v1
kind: Secret
metadata:
  name: "payment"
  namespace: roboshop
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
-------------------

apiVersion: apps/v1
kind : Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "payment"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "payment"
    template:
      metadata:
        labels:
          project: "roboshop"
          tier: "data"
          app: "payment"     
      spec:
        containers:
        - name: payment
          image: payment:v1
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: "payment"
------
apiVersion: v1
kind: Service
metadata:
  name: "payment"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "payment" 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 

