apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: data
    app: mongodb
spec:
  replicas: {{.values.statefulset.replicas}}
  selector:
    matchLabels:
      project: roboshop
      tier: data
      app: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        tier: data
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: jagadevops321/mongodb:{{.values.statefulset.version}}
        imagePullPolicy: Always
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
volumeClaimTemplates:
- metadata:
    name: mongodb
  spec:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "ebs-sc"
    resources:
      requests:
        storage: 1Gi