# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: "mongodb-config"
# data:
------------

apiVersion: apps/v1
kind : Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "mongodb"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "mongodb"
    template:
      metadata:
        labels:
          project: "roboshop"
          tier: "data"
          app: "mongodb"     
      spec:
        containers:
        - name: mongodb
          image: mongodb:v1
          imagePullPolicy: Always
------
apiVersion: v1
kind: Service
metadata:
  name: "mongodb"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "mongodb" 
  ports:
  - protocol: TCP
    port: 27107
    targetPort: 27017
 

