apiVersion: v1
kind: ConfigMap
metadata:
  name: "user"
  namespace: roboshop
data:
  MONGO: "true"

---

apiVersion: apps/v1
kind : Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: "roboshop"
    tier: "data"
    app: "user"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "roboshop"
      tier: "data"
      app: "user"
  template:
    metadata:
      labels:
        project: "roboshop"
        tier: "data"
        app: "user"     
    spec:
      containers:
      - name: user
        image: jagadevops321/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: "user"
---
apiVersion: v1
kind: Service
metadata:
  name: "user"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "user" 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
 

