apiVersion: v1
kind: Service
metadata:
  name: "catalogue"
  namespace: roboshop
spec:
  selector:
    project: "roboshop"
    tier: "data"
    app: "catalogue" 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080